[alias.image-build]
exec = "neuro-extras image build"
options = [ "-f, --file path to the Dockerfile within CONTEXT", "--build-arg build arguments for Docker", "-e, --env environment variables for container", "-v, --volume list of volumes for container",]
args = "CONTEXT IMAGE_URI"

[alias.seldon-init-package]
exec = "neuro-extras seldon init-package"
args = "URI_OR_PATH"

[alias.image-transfer]
exec = "neuro-extras image transfer"
args = "SOURCE DESTINATION"

[alias.data-transfer]
exec = "neuro-extras data transfer"
args = "SOURCE DESTINATION"

[alias.data-cp]
exec = "neuro-extras data cp"
options = [ "-c, --compress Compress source files", "-x, --extract Extract downloaded files", "-e, --env environment variables for container", "-v, --volume list of volumes for container",]
args = "SOURCE DESTINATION"
