repos:
- repo: local
  hooks:
  - id: gen-cli-docs
    name: Generate CLI docs
    language: system
    entry: make docs
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
- repo: https://github.com/asottile/yesqa
  rev: v1.5.0
  hooks:
  - id: yesqa
- repo: https://github.com/PyCQA/isort
  rev: '6.0.1'
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: '25.1.0'
  hooks:
  - id: black
    language_version: python3   # Should be a command that runs python3.6+
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: "^docs/"
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: check-symlinks
  - id: debug-statements
# Another entry is required to apply file-contents-sorter to another file
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: file-contents-sorter
    files: |
      docs/spelling_wordlist.txt|
      .gitignore
- repo: https://github.com/asottile/pyupgrade
  rev: 'v3.20.0'
  hooks:
  - id: pyupgrade
    args: ['--py38-plus']
- repo: https://github.com/PyCQA/flake8
  rev: '7.3.0'
  hooks:
  - id: flake8
    exclude: "^docs/"
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint-docker
    args:
    - -ignore
    - 'SC2155:'
    - -ignore
    - 'SC2086:'
    - -ignore
    - 'SC1004:'
    - -ignore
    - 'SC2193:'
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.33.3
  hooks:
  - id: check-github-actions
ci:
  # pre-commit ci do not install dependencies from setup.py
  skip:
  - gen-cli-docs
  - actionlint-docker
  - check-github-actions
