name: "Cleanup after CI tests"

on:
  schedule:
  - cron: 0 5 * * *
  # temporarly, to verify it's working
  pull_request:
    branches: [master]

permissions:
  packages: write

jobs:
  posttest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements/cleanup.txt

    - name: Delete test image
      env:
        GH_TOKEN: ${{ secrets.BOT_APP_ID }}
        GH_PASSWORD: ${{ secrets.BOT_PRIVATE_KEY }}
        GH_REPO_NAME: neuro-extras
        STALE_DAYS: "7"
      run: |
        python .github/workflows/cleanup.py
